version: 1.7.0-dev-{build}

only_commits:
  files:
  - src/
  - .appveyor.yml
  - CMakeLists.txt

pull_requests:
  do_not_increment_build_number: true

# Start builds on tags only (GitHub and BitBucket)
skip_non_tags: false

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

# Even with `skip_branch_with_pr: true` appveyor builds that branch
# for the first time.
branches:
  only:
  - master

artifacts:
- path: '**/celestia-*.7z'
  name: win

# Build worker image (VM template)
image: "Visual Studio 2019"

# clone directory
clone_folder: c:\projects\celestia

# set clone depth
clone_depth: 1

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform:
- x86

environment:
  Qt5_DIR: 'C:\Qt\5.10\msvc2015'
  PATH: '%Qt5_DIR%\bin;%PATH%'

# scripts that run after cloning repository
init:
- call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %platform%

install:
- cd c:\tools\vcpkg
- vcpkg --triplet=x86-windows install --recurse libpng libjpeg-turbo gettext luajit fmt libepoxy eigen3 brotli bzip2 zlib freetype ffmpeg cspice
- cd %APPVEYOR_BUILD_FOLDER%

build_script:
- cmd: >-
    git submodule update --init

    mkdir build

    cd build

    cmake -DCMAKE_PREFIX_PATH=%Qt5_DIR% -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DENABLE_SPICE=ON -DENABLE_TOOLS=ON -DENABLE_TESTS=ON -DENABLE_SDL=OFF ..

    cmake --build . --config RelWithDebInfo -- /maxcpucount:4 /nologo

    set CTEST_OUTPUT_ON_FAILURE=1

    copy src\celestia\RelWithDebInfo\*.dll test\unit\RelWithDebInfo\

    ctest -C RelWithDebInfo

after_build:
  - cmd: >-
      cd c:\projects\celestia\build\src\celestia

      7z a celestia-dep.x86.7z RelWithDebInfo\*

      7z a celestia-win.x86.7z win32\RelWithDebInfo\*

      windeployqt --no-angle --no-opengl-sw --no-translations --no-system-d3d-compiler qt\RelWithDebInfo\

      7z a celestia-qt.x86.7z qt\RelWithDebInfo\*

      cd ..\tools

      7z a celestia-tools.x86.7z xyzv2bin\RelWithDebInfo\*.exe spice2xyzv\RelWithDebInfo\*.exe

#on_failure:
#- type "c:\projects\celestia\build\CMakeFiles\CMakeOutput.log"
#- type "c:\projects\celestia\build\CMakeFiles\CMakeError.log"
#- type "c:\projects\celestia\build\CMakeCache.txt"

# build cache to preserve files/folders between builds
cache: c:\tools\vcpkg\installed\
