dist: xenial
osx_image: xcode11.4
language: cpp
sudo: true

git:
  depth: 1
  quiet: true

notifications:
  email: false

os:
- linux
- osx

env:
- LUA=jit-5.1
- LUA=5.2
- LUA=5.3

matrix:
  exclude:
  - os: osx
    env: LUA=jit-5.1
  - os: osx
    env: LUA=5.2
  - os: linux
    env: LUA=5.2

before_script:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt install -y liblua${LUA}-dev; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ] ; then brew link gettext --force; fi
- mkdir build
- cd build

script:
- cmake -DENABLE_SPICE=ON -DENABLE_TOOLS=ON -DENABLE_TTF=ON -DENABLE_TESTS=ON -DENABLE_SDL=ON ..
- make -j $(nproc || echo 4)
- CTEST_OUTPUT_ON_FAILURE=1 ctest

addons:
  apt:
    packages:
    - libeigen3-dev
    - libepoxy-dev
    - libtheora-dev
    - libjpeg-dev
    - libpng-dev
    - libglu1-mesa-dev
    - qtbase5-dev
    - qtbase5-dev-tools
    - libqt5opengl5-dev
    - libfreetype6-dev
    - libsdl2-dev
  homebrew:
    packages:
    - eigen
    - cspice
    - fmt
    - jpeg
    - gettext
    - libpng
    - lua
    - qt5
    - freetype
    - libepoxy
    - sdl2
    update: true
